version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    # volumes:
    #   - ./.pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tacostats
      POSTGRES_USER: tacostats
      POSTGRES_PASSWORD: tacostats
