AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tacostats v1.2.4

  periodically grab comments from the r/neoliberal DT and gather some basic statistics

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Resources:
  ###############
  # Harvester
  ###############
  Harvester:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 256
      ImageUri: 676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:v1.2.4
      ImageConfig:
        Command: 
          - tacostats.harvester.lambda_handler
      Role: arn:aws:iam::676444348764:role/tacostats
      Events:
        # schedules in utc, et equivs: 12,16,21
        Cron:
          Type: Schedule
          Properties:
            Schedule: cron(5/10 * * * ? *)
            Enabled: True       
    Metadata:
      Dockerfile: lambda.Dockerfile
      DockerContext: "."

  # post a recap of yesterday's stats in the morning
  HarvesterRecap:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 256
      ImageUri: 676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:v1.2.4
      ImageConfig:
        Command: 
          - tacostats.harvester.lambda_handler
      Environment:
        Variables:
          RECAP: True
      Role: arn:aws:iam::676444348764:role/tacostats
      Events:
        Cron:
          Type: Schedule
          Properties:
            Schedule: cron(0 7 * * ? *)
            Enabled: True       
    Metadata:
      Dockerfile: lambda.Dockerfile
      DockerContext: "."

  ###############
  # Statistics
  ###############
  Stats:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 256
      ImageUri: 676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:v1.2.4
      ImageConfig:
        Command: 
          - tacostats.stats.lambda_handler
      Role: arn:aws:iam::676444348764:role/tacostats
      Environment:
        Variables:
          USE_EXISTING: True
      Events:
        # schedules in utc, et equivs: 12,16,21
        Cron:
          Type: Schedule
          Properties:
            Schedule: cron(0 16,20,1 * * ? *)
            Enabled: True       
    Metadata:
      Dockerfile: lambda.Dockerfile
      DockerContext: "."

  # post a recap of yesterday's stats in the morning
  StatsRecap:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 256
      ImageUri: 676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:v1.2.4
      ImageConfig:
        Command: 
          - tacostats.stats.lambda_handler
      Environment:
        Variables:
          RECAP: True
          USE_EXISTING: True
      Role: arn:aws:iam::676444348764:role/tacostats
      Events:
        # schedules in utc, 9et
        Cron:
          Type: Schedule
          Properties:
            Schedule: cron(0 13 * * ? *)
            Enabled: True       
    Metadata:
      Dockerfile: lambda.Dockerfile
      DockerContext: "."

  ###############
  # Keywords
  ###############
  Keywords:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 384
      ImageUri: 676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:v1.2.4
      ImageConfig:
        Command: 
          - tacostats.keywords.lambda_handler
      Environment:
        Variables:
          USE_EXISTING: True
      Role: arn:aws:iam::676444348764:role/tacostats
      Events:
        # schedules in utc, et equiv: 16,21
        Cron:
          Type: Schedule
          Properties:
            Schedule: cron(17 20,1 * * ? *)
            Enabled: True
    Metadata:
      Dockerfile: lambda.Dockerfile
      DockerContext: "."

  # post a recap of yesterday's keywords in the morning
  KeywordsRecap:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 384
      ImageUri: 676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:v1.2.4
      ImageConfig:
        Command: 
          - tacostats.keywords.lambda_handler
      Environment:
        Variables:
          RECAP: True
          USE_EXISTING: True
      Role: arn:aws:iam::676444348764:role/tacostats
      Events:
        # schedules in utc, 10et
        Cron:
          Type: Schedule
          Properties:
            Schedule: cron(0 14 * * ? *)
            Enabled: True       
    Metadata:
      Dockerfile: lambda.Dockerfile
      DockerContext: "."

  ###############
  # UserStats
  ###############
  UserStats:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 30
      PackageType: Image
      MemorySize: 256
      ImageUri: 676444348764.dkr.ecr.us-west-2.amazonaws.com/tacostats:v1.2.4
      ImageConfig:
        Command: 
          - tacostats.userstats.lambda_handler
      Role: arn:aws:iam::676444348764:role/tacostats
      Events:
        Queue:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-west-2:676444348764:tacostats-pinger
            BatchSize: 10
            Enabled: true
    Metadata:
      Dockerfile: lambda.Dockerfile
      DockerContext: "."

