version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tacostats"
s3_bucket = "inhumantsar-tacostats-cfn"
s3_prefix = "tacostats"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["Harvester=390721581096.dkr.ecr.us-east-2.amazonaws.com/tacostats:v1.5.4", "HarvesterRecap=390721581096.dkr.ecr.us-east-2.amazonaws.com/tacostats:v1.5.4", "Stats=390721581096.dkr.ecr.us-east-2.amazonaws.com/tacostats:v1.5.4", "StatsRecap=390721581096.dkr.ecr.us-east-2.amazonaws.com/tacostats:v1.5.4", "Keywords=390721581096.dkr.ecr.us-east-2.amazonaws.com/tacostats:v1.5.4", "KeywordsRecap=390721581096.dkr.ecr.us-east-2.amazonaws.com/tacostats:v1.5.4", "UserStats=390721581096.dkr.ecr.us-east-2.amazonaws.com/tacostats:v1.5.4"]
